### ISSUE TITLE
BHAnimation modules

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-RO/USProbesPack#4]
Are you going to be releasing your recomile of the dll?  I'm asking because I'm working on updating a mod which uses it, and don't want to conflict with your stuff

**Comment by raidernick** [comment]
https://github.com/raidernick/BDAnimationModules/releases/tag/v0.6.3

**Comment by linuxgurugamer** [comment]
thanks.  Are you going to make this an official release?

**Comment by raidernick** [comment]
no
