### ISSUE TITLE
RN_scansat.cfg and RP-1 V1.1.x Contract Problem

### ISSUE THREAD

**Issue by JohnMcLane4** [KSP-RO/USProbesPack#5]
I made two installs with the new RP-1 v1.1.1 in 1.3.1 and 1.6.1 and if i add US Probepack to the install, the RP-1 contracts disappear. I cant select them in the new game settings and also in existing games no contracts are available anymore.

I deleted the rn_scansat.cfg from rn_us_probes and the contracts are available again. 
There seems to be an issue.
The 1.6.1 Log if that helps.
https://drive.google.com/open?id=1seFb7BhtHsZJJ6m7fAMRSJM2JkDKXM-L

Thanks for the great probe pack, always a must in every install!

**Comment by raidernick** [comment]
I don't support RP1 at all this is not the right place to ask this. Ask on the RP1 git.

**Comment by Peter-JY** [comment]
Link of this issues in RP-0‘s issues: [https://github.com/KSP-RO/RP-0/issues/1245 (issues #1245)](https://github.com/KSP-RO/RP-0/issues/1245)
